Add support for multiple templates dirs in configuration app
cloudentity/openbanking-quickstart pull request #18
Opened 2021-05-28 11:35 UTC by ikawalec

- add support for multiple templates dirs in configuration app
- cleanups

2021-05-28 11:42 UTC, mbilski requested changes

2021-05-28 11:42 UTC, mbilski commented on apps/configuration/templates.go
> +func LoadTemplates(dirs string, variablesFile *string) (Templates, error) {
shoudn't this take []string as dirs?

2021-05-28 11:50 UTC, ikawalec commented on apps/configuration/templates.go
> +func LoadTemplates(dirs string, variablesFile *string) (Templates, error) {
fixed

2021-05-31 07:20 UTC, mbilski approved these changes

2021-05-31 08:34 UTC, merged