Feature/aut 6878-2 Part 2 Extend financroo app to support FDX
cloudentity/openbanking-quickstart pull request #224
Opened 2022-08-24 20:08 UTC by Olb

## AUT-6878 - [Extend financroo app to support FDX Part 2 ](https://cloudentity.atlassian.net/browse/AUT-6878)

## Description

This PR is Part 2 for extending Financroo TPP to support FDX. 

## Information for QA

- [x] Is QA testing required?
- [ ] Does PR contain unit tests?
- [ ] Should QA create E2E tests for the change?

2022-09-06 13:05 UTC, ikawalec requested changes

2022-09-06 14:47 UTC, Olb commented on apps/bank/fdx_get_accounts_handler.go
> +		if err = json.Unmarshal(jsonStr, &depositAccount); err != nil {
The json includes an []interface{} for accounts. So it is returned as `map[string]interface`. If you try to unmarshal directly to deposit account it fails so this is how I worked around it. Is there a better way?

2022-09-06 23:30 UTC, Olb commented on apps/financroo-tpp/server.go
> +func newMtlsHTTPClient(config Config) (*http.Client, error) {
we can and should and are. I messed up. That wasn't being used. It is removed now

2022-09-07 13:11 UTC, ikawalec approved these changes

2022-09-08 12:31 UTC, RajmundNowicki approved these changes

2022-09-08 12:38 UTC, merged