Feature/aut 3323 cypress restore ignored tests
cloudentity/openbanking-quickstart pull request #66
Opened 2021-08-18 14:57 UTC by RajmundNowicki

2021-08-18 15:40 UTC, mzerko-cloudentity approved these changes

2021-08-18 18:38 UTC, piotrek-janus requested changes

2021-08-18 18:38 UTC, piotrek-janus commented on consent/admin-portal/web/app/src/components/utils.tsx
> +      <Chip type="inactive" id="status-inactive">Inactive</Chip>
it is used in a list so it will result in duplicated ids

2021-08-19 11:51 UTC, piotrek-janus approved these changes

2021-08-19 11:53 UTC, merged